require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Gemspec/OrderedDependencies:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect

Layout/LineLength:
  AllowedPatterns:
    - "\\s*#\\s*@see.*"

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes
